modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"
issueTrackerURL=""

[[mods]] #mandatory
modId="improved_slimes" #mandatory
version="1.19.2-1.1.0" #mandatory
displayName="Improved Slimes" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/improved-slimes"
logoFile="logo.png" #optional
authors="ISenseHostility" #optional
description='''
Improves slimes to be more reflective of their slimy properties.
    '''

[[dependencies.improved_slimes]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.improved_slimes]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2, 1.20)"
ordering="NONE"
side="BOTH"
